### ISSUE TITLE
Installation fails on rapsberrypi2

### ISSUE THREAD

**Issue by irekzielinski** [filcole/pycarwings2#8]
Any pointers would be appreciated:
(my version of Pi has Python 3.4.2, as it aborts on regression test? - maybe we could skip it on this older version of python?)

```
pi@RaspberryPi ~/scripts/leaf $ sudo pip3 install git+https://github.com/filcole/pycarwings2.git
Downloading/unpacking git+https://github.com/filcole/pycarwings2.git
  Cloning https://github.com/filcole/pycarwings2.git to /tmp/pip-bhr9qlwb-build
  Running setup.py (path:/tmp/pip-bhr9qlwb-build/setup.py) egg_info for package from git+https://github.com/filcole/pycarwings2.git
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-bhr9qlwb-build/setup.py", line 61, in <module>
        tests_require=['pytest', 'pytest-cov', 'pytest-flake8'],
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 874, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 886, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 338, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1063, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 68, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 114, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 67, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 43, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-90w9knx3/pytest-runner-4.2/setup.py", line 76, in <module>
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/easy_install-90w9knx3/pytest-runner-4.2/setuptools_scm-3.1.0-py3.4.egg/setuptools_scm/integration.py", line 10, in version_keyword
      File "/tmp/easy_install-90w9knx3/pytest-runner-4.2/setuptools_scm-3.1.0-py3.4.egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_outdated
    setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-bhr9qlwb-build/setup.py", line 61, in <module>

    tests_require=['pytest', 'pytest-cov', 'pytest-flake8'],

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 262, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 631, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 874, in best_match

    return self.obtain(req, installer)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 886, in obtain

    return installer(requirement)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 338, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 666, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1063, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 68, in run_setup

    DirectorySandbox(setup_dir).run(runner)

  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 114, in run

    return func()

  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 67, in runner

    _execfile(setup_script, ns)

  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 43, in _execfile

    exec(code, globals, locals)

  File "/tmp/easy_install-90w9knx3/pytest-runner-4.2/setup.py", line 76, in <module>

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "/tmp/easy_install-90w9knx3/pytest-runner-4.2/setuptools_scm-3.1.0-py3.4.egg/setuptools_scm/integration.py", line 10, in version_keyword

  File "/tmp/easy_install-90w9knx3/pytest-runner-4.2/setuptools_scm-3.1.0-py3.4.egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_outdated

setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-bhr9qlwb-build
Storing debug log for failure in /root/.pip/pip.log
pi@RaspberryPi ~/scripts/leaf $ 

```

**Comment by filcole** [comment]
I've initially concentrated on python3.5 because that's what's in debian stable. Going to need to get a python3.4 environment up and running to test this.

Note that this is now in PyPi, so does `pip3 install pycarwings2` install?  I expect it won't.

**Comment by irekzielinski** [comment]
thanks for the prompt response 👍 

what should be install command using pypi?
I was following "Installation" commands as described on the intro page:
```
pip3 install requests pycryptodome configparser
pip3 install git+https://github.com/filcole/pycarwings2.git
```
So those are out of date right?

**Comment by filcole** [comment]
You're dead right.  I'll update them now.  🤦‍♂️

**Comment by irekzielinski** [comment]
After long battle managed to install pyton 3.7 on my pi (had to compile new openssl).
Got it working with your library and it gets the battery status!
THANKS a lot for your work and help!
