### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by filcole** [filcole/pycarwings2#9]
RoadkillUK reported the following error:  https://community.home-assistant.io/t/nissan-leaf-component-s-platform/38663/149 . Looks like an error in pycarwings.

2019-01-05 18:45:45 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python36-32\lib\site-packages\homeassistant\components\nissan_leaf.py", line 234, in async_update_data
    await self.async_refresh_data(now)
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python36-32\lib\site-packages\homeassistant\components\nissan_leaf.py", line 339, in async_refresh_data
    climate_response = await self.async_get_climate()
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python36-32\lib\site-packages\homeassistant\components\nissan_leaf.py", line 415, in async_get_climate
    self.leaf.get_latest_hvac_status
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Lee\AppData\Roaming\.homeassistant\deps\Python36\site-packages\pycarwings2\pycarwings2.py", line 395, in get_latest_hvac_status
    return CarwingsLatestClimateControlStatusResponse(response)
  File "C:\Users\Lee\AppData\Roaming\.homeassistant\deps\Python36\site-packages\pycarwings2\responses.py", line 312, in __init__
    racr["OperationResult"] and
TypeError: list indices must be integers or slices, not str

**Comment by filcole** [comment]
**From a 2014 24kWh Leaf**

2019-01-05 19:54:06 DEBUG (SyncWorker_18) [pycarwings2.pycarwings2] invoking carwings API: https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/RemoteACRecordsRequest.php
2019-01-05 19:54:06 DEBUG (SyncWorker_18) [pycarwings2.pycarwings2] params: {
   "DCMID": "<snip>",
   "RegionCode": "NE",
   "TimeFrom": "2018-11-25T22:03:22Z",
   "VIN": "<snip>",
   "custom_sessionid": "<snip>,
   "initial_app_strings": "geORNtsZe5I4lRGjG9GZiA",
   "lg": "en_GB",
   "tz": "Europe/Paris"
}
2019-01-05 19:54:09 DEBUG (SyncWorker_18) [pycarwings2.pycarwings2] Response HTTP Status Code: 200
2019-01-05 19:54:09 DEBUG (SyncWorker_18) [pycarwings2.pycarwings2] Response HTTP Response Body: b'{"status":200,"RemoteACRecords":[]}'

[Dartcarwings handles](https://gitlab.com/tobiaswkjeldsen/dartcarwings/blob/d6b0b1c3f3e84356db3bce744a40d172ae817f09/lib/src/carwings_hvac.dart) this by assuming that the climate control is off

```dart
    // Sometimes racr is simply empty
    // If it is empty HVAC is not on (an assumption)
    this.isRunning = racr.length > 0 && racr['OperationResult'] != null &&
        racr['OperationResult'].toString().startsWith('START') &&
        racr['RemoteACOperation'] == 'START';
    if(racr.length > 0) {
      this.preACTemp = racr['PreAC_temp'];
      this.preACTempUnit = racr['PreAC_unit'];
      this.incTemp = racr['Inc_temp'];
```

**Comment by filcole** [comment]
Fixed by commit https://github.com/filcole/pycarwings2/commit/394cfb9d4c2f68ed408d770e5032360d9a38e552.   We handle it the same way as dartcarwings.  Release 2.3 has been uploaded to PyPi
